# Generated by Django 4.0.5 on 2022-06-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='imagen/blog', verbose_name='Imagen')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Blog Personal',
                'verbose_name_plural': 'Blogs Personales',
                'ordering': ['name'],
            },
        ),
    ]
